apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rupbot
  name: rupbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rupbot
  template:
    metadata:
      labels:
        app: rupbot
    spec:
      containers:
      - env:
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
        image: mdshajib/rupbot
        imagePullPolicy: Always
        name: rupbot
        ports:
        - containerPort: 9000
          name: rupbot
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html/storage/logs
          name: logs
        - mountPath: /var/www/html/storage/framework/views
          name: views
        - mountPath: /var/www/html
          name: rupbot-storage
      volumes:
      - name: rupbot-storage
        persistentVolumeClaim:
          claimName: rupbot-pvc
      - name: logs
      - name: views
