apiVersion: v1
kind: ConfigMap
metadata:
  name: rupbot-nginx-config
  labels:
    app: rupbot-nginx
data:
  config : |
    server {
      listen 80;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /var/www/html/public;
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location /hello {
        add_header Content-Type text/plain;
        return 200 "hello url";
      }
      
      location ~ .php$ {
          proxy_pass rupbot-service:9000;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }