apiVersion: v1
kind: ConfigMap
metadata:
  name: rupbot-nginx-config
  labels:
    app: rupbot-nginx
data:
  config : |
    server {
      listen 80;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /var/www/rupbot;
      index /public/index.php;
      location / {
          try_files $uri $uri/ /public/index.php?$query_string;
      }

      location /hello {
        add_header Content-Type text/plain;
        return 200 "hello url";
      }
      
      location ~ .php$ {
          fastcgi_pass rupbot-service:9000;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }

      location ~* \.(css|js|jpg|jpeg|png|gif|ico)$ {
          expires max;
          log_not_found off;
          access_log off;
      }

    }