apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rupbot-nginx
  name: rupbot-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rupbot-nginx
  template:
    metadata:
      labels:
        app: rupbot-nginx
    spec:
      containers:
      - image: nginx:1.25.3-alpine-slim
        imagePullPolicy: Always
        name: rupbot-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: site.conf
          name: rupbot-nginx-config
        name: config
